project:
  type: website

website:
  title: "Git for librarians"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - Setup_and_instructions.qmd
      - section: "Getting to know Git(hub)"
        contents:
          - What_is_git.qmd
          - Git_Github_Gitlab.qmd
          - The_history.qmd
      - section: "Github online and version control"
        contents:
          - Git_online.qmd
          - Creating_your_first_repository.qmd
          - Your_first_commit.qmd
          - Branching.qmd
          - Pull_requests.qmd
      - section: "Collaboration on Github online"
        contents:
          - Forking.qmd
          - Issues.qmd
      - section: "Git on your local machine"
        contents: 
          - Github_desktop.qmd
          - Github_desktop2.qmd
      - section: "Version control"
        contents: 
          - Version_control.qmd
      - Glossary.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



editor: visual

